import java.text.SimpleDateFormat

def numero1 = 100
def numero2 = 200
def suma = 0
def resta = 0
def multiplicacion = 0
def division = 0

pipeline
{
  agent any
  
  options
  {
    timeout(time:10, unit: 'SECONDS')
  }
      
  environment
  {
    RUTA_ABSOLUTA = "C:\\ejercicio_3.txt"
  }
   
  stages
  {
    stage("Stage 1 Operaciones Aritmeticas")
    {
      steps
      {
        script
        {
          suma = numero1 +  numero2
          println "El resultado de la suma de: " + numero1
          println "y: " + numero2
          println "es igual a: " + suma
        }
      }
    }
  }
  
  post
  {
    always
    {
        echo "El Ejercicio_3 se ejecuto. "
    }
      
    failure
    {
        script
        {
          println 'EL pipeline fallo'
          def errorMessage = currentBuild.rawBuild.getLog(1000).join('\n')
          println 'Detalles del error: ${errorMessage}'
          mail to: "victorm.nieva@inetum.com", subject: "Pipeline Fallo", body: "El pipeline no se ejecuto."
        }
    }
      
    unstable
    {
      echo "El pipeline no se ejecuto de forma estable."
    }
      
    success
    {
      echo "Mensaje a ejecutar si salio todo bien"        
    }
  }
}
  



