import java.text.SimpleDateFormat

def numero1 = 100
def numero2 = 200
def suma = 0
def resta = 0
def multiplicacion = 0
def division = 0

pipeline
{
  agent any
  
  options
  {
    timeout(time:10, unit: 'SECONDS')
  }
      
  environment
  {
    RUTA_ABSOLUTA = "C:\\ejercicio_3.txt"
  }
   
  stages
  {
    stage("Stage 1: Operaciones Aritmeticas")
    {
      steps
      {
        script
        {
          suma = numero1 +  numero2
          println "El resultado de la suma de: " + numero1
          println "y: " + numero2
          println "es igual a: " + suma
        }
      }
  
      steps
      {
        script
        {
          resta = numero1 - numero2
          println "El resultado de la resta de: " + numero1
          println "y: " + numero2
          println "es igual a: " + resta
        }
      }
              
      steps
      {
        script
        {
          multiplicacion = numero1 * numero2
          println "El resultado de la multiplicacion de: " + numero1
          println "y: " + numero2
          println "es igual a: " + multiplicacion
        }
      }
            
      steps
      {
        script
        {
          if(numero1 == 0 || numero2 == 0) {
            division = "No se puede dividir por 0"
          } else {
            division = numero1 / numero2
            println "El resultado de la division de: " + numero1
            println "y: " + numero2
            println "es igual a: " + division
          }
         }
        }
      }
  
      stage("Stage 2: Comando tipo bat")
      {
        steps
        {
          bat "ipconfig /flushdns"
        }  
      }
                
      stage("Stage 3: Generar fichero")
      {
        steps
        {
          script
          {
            dia = new Date()
            formato = new SimpleDateFormat("dd/MM/yyyy")
            fechaFormato = formato.format(dia)
            contenido =  "Este ejercicio ha sido ejecutado el dia: " + fechaFormato + "\n El numero1 es: " + numero1 + "\n El numero2 es: " + numero2 + "\n La suma es: " + suma + "\n La resta es: " + resta + "\n La multiplicacion es: " + multiplicacion + "\n La division es: " + division
            writeFile(file: env.RUTA_ABSOLUTA, text: contenido)
            println "Se ha generado el fichero en la rula: " + env.RUTA_ABSOLUTA
          }
        }
      }
    }
    post
    {
      always
      {
        echo "El Ejercicio_3 se ejecuto. "
      }
      
      failure
      {
        script
        {
          println 'EL pipeline fallo'
          def errorMessage = currentBuild.rawBuild.getLog(1000).join('\n')
          println 'Detalles del error: ${errorMessage}'
          mail to: "victorm.nieva@inetum.com", subject: "Pipeline Fallo", body: "El pipeline no se ejecuto."
        }
      }
      
      unstable
      {
        echo "El pipeline no se ejecuto de forma estable."
      }
      
      success
      {
        echo "Mensaje a ejecutar si salio todo bien"        
      }
    }
  }
  



